Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.define "dockerhost-031eeddf-3210-11e5-8e1d-0242ac1107a2", autostart: false do |docker|
  	docker.vm.provision "docker"
  	docker.vm.box = "yungsang/boot2docker"
  	docker.vm.box_check_update = false
    docker.vm.network "forwarded_port", guest: 2735, host: 2375, auto_correct: true
  	
  	
  	
  	  docker.vm.network "forwarded_port", guest: 38888, host: 38888, auto_correct: true
  	
  	docker.vm.provider :virtualbox do |vb|
  		vb.name = "dockerhost-031eeddf-3210-11e5-8e1d-0242ac1107a2"
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off", "--natdnshostresolver1", "off"]
  	end
  end

  
  

  
  	config.vm.define "stickypipe_receiver" do |svc|
      svc.vm.synced_folder "../stickypipe_receiver", "/go/src/app"
      svc.vm.provider "docker" do |d|
        d.build_dir = "../stickypipe_receiver"
        d.force_host_vm = true
        d.ports = ["38888:8888"]
        d.name = "stickypipe_receiver"
        
        d.vagrant_vagrantfile = "./Vagrantfile"
        d.vagrant_machine = "dockerhost-031eeddf-3210-11e5-8e1d-0242ac1107a2"
      end
    end
  
end
